### ISSUE TITLE
Help with configurating\error?

### ISSUE THREAD

**Issue by Makein** [rekaXua/demosaic_project#1]
```
D:\demosaic_project-1.0>pip3 install -r requirements.txt
Collecting glob3
  Using cached glob3-0.0.1.tar.gz (669 bytes)
ERROR: Could not find a version that satisfies the requirement torch==1.2.0 (from -r requirements.txt (line 2)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.2.0 (from -r requirements.txt (line 2))



D:\demosaic_project-1.0>python demosaic_project_ESRGAN.py
Traceback (most recent call last):
  File "demosaic_project_ESRGAN.py", line 1, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

I download demosaic_project-1.0.rar, extracted and downloaded 4x_FatalPixels_340000_G.pth (placed it in model folder)
Have installed last python 3.8.2

**Comment by rekaXua** [comment]
Your error is with installing PyTorch. (https://pytorch.org/)
So if you have NVidia GPU and CUDA 10.1 installed, you can use this command to install PyTorch
"pip3 install torch===1.4.0 torchvision===0.5.0 -f https://download.pytorch.org/whl/torch_stable.html"
or "pip3 install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html" if you want cpu-only version. 
Then just remove "torch===1.2.0" line in requirements.txt, and run "pip3 install -r requirements.txt" once again

**Comment by Makein** [comment]
D:\demosaic_project-1.0>pip3 install torch===1.4.0 torchvision===0.5.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch===1.4.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch===1.4.0

D:\demosaic_project-1.0>pip3 install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.4.0+cpu (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.4.0+cpu

If I remove "torch===1.2.0" line in requirements.txt, and run "pip3 install -r requirements.txt" 
D:\demosaic_project-1.0>pip3 install -r requirements.txt
Requirement already satisfied: glob3 in c:\users\makein\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 1)) (0.0.1)
ERROR: Could not find a version that satisfies the requirement torch===1.2.0 (from -r requirements.txt (line 2)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch===1.2.0 (from -r requirements.txt (line 2))

D:\demosaic_project-1.0>pip3 install -r requirements.txt
Requirement already satisfied: glob3 in c:\users\makein\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 1)) (0.0.1)
Collecting torchvision
  Using cached torchvision-0.2.2.post3-py2.py3-none-any.whl (64 kB)
ERROR: Could not find a version that satisfies the requirement opencv_python==4.0.0.21 (from -r requirements.txt (line 3)) (from versions: 3.4.8.29, 3.4.9.31, 3.4.9.33, 4.1.2.30, 4.2.0.32, 4.2.0.34)
ERROR: No matching distribution found for opencv_python==4.0.0.21 (from -r requirements.txt (line 3))

**Comment by rekaXua** [comment]
The CPU should work regardless now. As for GPU support, I think that is a problem with CUDA, perhaps you have an older GPU? Is it older than GTX6xx?

**Comment by Makein** [comment]
> 
> 
> The CPU should work regardless now. As for GPU support, I think there is a problem with CUDA, perhaps you have an older GPU? Is it older than GTX6xx?

I have "Gigabyte nvidia gtx 780ti" 
I installed "[cuda_10.2.89_win10_network.exe](https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exenetwork)" from here

**Comment by rekaXua** [comment]
> I installed "[cuda_10.2.89_win10_network.exe](https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exenetwork)" from here
Also I think you need a specific version of CUDA for pytorch, if it requires 10.1 then it may not be compatible with 10.2, thy 10.1 without updates from here https://developer.nvidia.com/cuda-toolkit-archive

**Comment by Makein** [comment]
Driver version 445.87
CUDA 10.1 don't want to install... =\
Say new version available, even offline...

**Comment by rekaXua** [comment]
Hmmm, I have found that: "GTX 780 has the cuda cc of 3.5, which is not supported anymore in 1.3.1. You'll have to build PyTorch from source" [here](https://github.com/pytorch/pytorch/issues/31285). So I guess you'll actually would need to install old PyTorch 1.2.0 like said [here](https://pytorch.org/get-started/previous-versions/) with command "pip3 install torch===1.2.0 torchvision===0.4.0 -f https://download.pytorch.org/whl/torch_stable.html" and I think you would need old CUDA 10.0 👺

**Comment by Makein** [comment]
> 
> 
> Hmmm, I have found that: "GTX 780 has the cuda cc of 3.5, which is not supported anymore in 1.3.1. You'll have to build PyTorch from source" [here](https://github.com/pytorch/pytorch/issues/31285). So I guess you'll actually would need to install the old PyTorch 1.2.0 like said [here](https://pytorch.org/get-started/previous-versions/) with command "pip3 install torch===1.2.0 torchvision===0.4.0 -f https://download.pytorch.org/whl/torch_stable.html" and I think you would also need the old CUDA 10.0 👺

YES, now it's working!
Thanks!
Never think that they would drop support of my video card, ha~ha
