### ISSUE TITLE
Glob3 can't be downloaded. Can I upload it?

### ISSUE THREAD

**Issue by werfweqrweq** [rekaXua/demosaic_project#2]
glob3下载不到了，可以给一个吗？

**Comment by rekaXua** [comment]
What version of Python are you using?

**Comment by rekaXua** [comment]
Oh, I think something happened to glob repo. Here's the files for manual Installation:
https://pydoc.net/glob3/0.0.1/

**Comment by werfweqrweq** [comment]
python3。thanks

**Comment by werfweqrweq** [comment]
Which version of Python3 do you recommend?

**Comment by rekaXua** [comment]
Hmm, I never tried it on Python 3.8, so guess I'll recommend 3.7 :D

**Comment by Blizzardo1** [comment]
pydoc's repo is dead, any other suggestions while I continue my search for glob3?

**Comment by rekaXua** [comment]
oof. I've merged your pull, so I think it should work now!
Thanks! :D
