### ISSUE TITLE
Program refuses to function

### ISSUE THREAD

**Issue by KilluaZo1dyck** [rekaXua/demosaic_project#6]
the command python ```demosaic_project_ESRGAN.py --cpu```
does not run the program in cpu mode, because there seems to be something wrong with the code.

no matter what I do, I get this error:```   raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled```

**Comment by rekaXua** [comment]
Yeah, there was en error with calculation of available memory, though now you'll need to write the amount of RAM for the program to use if cpu mode is selected
